[package]
name = "vector_mq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

qp2p = "0.21.0"
tokio = { version = "1.11.0", feature = ["time"] }
anyhow = "1.0.43"
rand = "0.8.4"
bytes = "1.1.0"
